# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='objId',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
